

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: ShivamJhaa/ShivamJhaa@master
        with:
          WAKATIME_API_KEY: ${{ secrets.94557df9-737e-4d9a-88f4-29a18728a62f }}
          GH_TOKEN: ${{ secrets.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 }}
